// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMgBHKaYSS0-UR-CqEXy_LxEP4LpHvkrE',
    appId: '1:870501520419:web:669560b005e2b3d8114d96',
    messagingSenderId: '870501520419',
    projectId: 'hamosad-scouting-app',
    authDomain: 'hamosad-scouting-app.firebaseapp.com',
    databaseURL: 'https://hamosad-scouting-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hamosad-scouting-app.appspot.com',
    measurementId: 'G-3GQ0DC3E2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW6XB4IYoS5LTcjhJ-DEXgG7wDiUnKzqE',
    appId: '1:870501520419:android:a3c279a942571d7f114d96',
    messagingSenderId: '870501520419',
    projectId: 'hamosad-scouting-app',
    databaseURL: 'https://hamosad-scouting-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hamosad-scouting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx8153JEglN_3zJgtRvWCaGQnUQwraunA',
    appId: '1:870501520419:ios:aa2fbf4c33079fad114d96',
    messagingSenderId: '870501520419',
    projectId: 'hamosad-scouting-app',
    databaseURL: 'https://hamosad-scouting-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hamosad-scouting-app.appspot.com',
    androidClientId: '870501520419-igrt16smcsah59090i4c3h87hbham9mg.apps.googleusercontent.com',
    iosClientId: '870501520419-7trmqoi9fk2dpjm7q35nbipju4b6gjpn.apps.googleusercontent.com',
    iosBundleId: 'com.hamosad1657.hamosadScoutingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx8153JEglN_3zJgtRvWCaGQnUQwraunA',
    appId: '1:870501520419:ios:aa2fbf4c33079fad114d96',
    messagingSenderId: '870501520419',
    projectId: 'hamosad-scouting-app',
    databaseURL: 'https://hamosad-scouting-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hamosad-scouting-app.appspot.com',
    androidClientId: '870501520419-igrt16smcsah59090i4c3h87hbham9mg.apps.googleusercontent.com',
    iosClientId: '870501520419-7trmqoi9fk2dpjm7q35nbipju4b6gjpn.apps.googleusercontent.com',
    iosBundleId: 'com.hamosad1657.hamosadScoutingApp',
  );
}
